#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the compareTriplets function below.
def compareTriplets(a, b):
    A,B=0,0
    ans=[]
    
    for i in range(0,len(a)):
        if a[i]<b[i]:
            B=B+1
        elif a[i]>b[i]:
            A+=1
    ans.append(A)
    ans.append(B)
    return ans       


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    a = list(map(int, input().rstrip().split()))

    b = list(map(int, input().rstrip().split()))

    result = compareTriplets(a, b)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
