#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the plusMinus function below.
def plusMinus(arr):
    a,b,c=0,0,0
    for i in arr:
        if i>0:
            a+=1
        elif i<0:
            b+=1
        else:
            c+=1
    print(a/len(arr),end='\n')
    print(b/len(arr),end='\n')
    print(c/len(arr),end='\n')            


if __name__ == '__main__':
    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
